### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gatemezing** [rvesse/sparql-query-bm#4]
Hi @rvesse,
I've just downloaded this nice tool from sourceforge on Windows and wanted to give it a trial. 
I've tried benchmark.bat like this: 
benchmark.bat -q http://localhost/sparql -m queries.tsv -r 250 -w 20 -c results.csv  --logging
==output stdout==
Running in verbose mode, run with --quiet to disable
0
java.lang.ArrayIndexOutOfBoundsException: 0
        at net.sf.sparql.benchmarking.loader.mix.TsvMixLoader.parseLine(TsvMixLoader.java:61)
        at net.sf.sparql.benchmarking.loader.AbstractLineBasedMixLoader.parseFile(AbstractLineBasedMixLoader.java:66)
        at net.sf.sparql.benchmarking.loader.AbstractOperationMixLoader.load(AbstractOperationMixLoader.java:63)
        at net.sf.sparql.benchmarking.commands.AbstractCommand.applyStandardOptions(AbstractCommand.java:402)
        at net.sf.sparql.benchmarking.commands.BenchmarkCommand.run(BenchmarkCommand.java:156)
        at net.sf.sparql.benchmarking.commands.BenchmarkCommand.main(BenchmarkCommand.java:115)
		
This is how I've created the queries.tsv file 		
==queries.tsv ===
```
query	D:\sparql-query-bm-2.1.0\cmd\queries\q1.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q2.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q3.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q4.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q5.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q6.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q7.rq
query	D:\sparql-query-bm-2.1.0\cmd\queries\q8.rq
update	D:\sparql-query-bm-2.1.0\cmd\updates\q1.rq
```

How can I solve the error? Any pointer?

**Comment by rvesse** [comment]
Do you have an extra empty line at the end of the file?

I'm not sure that the code handles that correctly.

**Comment by gatemezing** [comment]
Yes, that's was the issue. Thanks! Now it seems to produce some results 👍
